#!/bin/sh
lb config noauto \
    --distribution trixie \
    --mirror-bootstrap "http://deb.debian.org/debian/" \
    --mirror-chroot "http://deb.debian.org/debian/" \
    --mirror-binary "http://deb.debian.org/debian/" \
    --mirror-chroot-security "http://deb.debian.org/debian-security/" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --linux-flavours "amd64" \
    --linux-packages "linux-image" \
    --debian-installer live \
    --debian-installer-gui true \
    --bootappend-live "boot=live components quiet splash" \
    --iso-volume "moonlightOS-Meow-v6" \
    --image-name "moonlightos-meow-v6.0" \
    --compression xz \
    "${@}"